version: "3.7"

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - TZ=Europe/London
    volumes:
      - ./config:/app/config
    ports:
      - 80:5055
